const APPLE_MUSIC_API = "https://api.music.apple.com/v1/me/library/playlists";

function authHeaders(developerToken: string, musicUserToken: string) {
  return {
    Authorization: `Bearer ${developerToken}`,
    "Music-User-Token": musicUserToken,
    "Content-Type": "application/json",
  };
}

function toTrackData(trackIds: string[]) {
  return trackIds.map((id) => ({ id, type: "songs" as const }));
}

/**
 * Create a new Apple Music library playlist.
 */
export async function createAppleMusicPlaylist(params: {
  developerToken: string;
  musicUserToken: string;
  name: string;
  description?: string;
  trackIds: string[];
}): Promise<{ playlistId: string }> {
  const { developerToken, musicUserToken, name, description, trackIds } =
    params;

  const body = {
    attributes: {
      name,
      ...(description ? { description } : {}),
    },
    relationships: {
      tracks: {
        data: toTrackData(trackIds),
      },
    },
  };

  const res = await fetch(APPLE_MUSIC_API, {
    method: "POST",
    headers: authHeaders(developerToken, musicUserToken),
    body: JSON.stringify(body),
  });

  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(
      `Apple Music create playlist failed: ${res.status} ${res.statusText} — ${text}`
    );
  }

  const json = (await res.json()) as { data: { id: string }[] };
  const playlistId = json.data?.[0]?.id;
  if (!playlistId) {
    throw new Error("Apple Music create playlist returned no playlist ID");
  }

  return { playlistId };
}

/**
 * Add tracks to an existing Apple Music library playlist.
 */
export async function addTracksToAppleMusicPlaylist(params: {
  developerToken: string;
  musicUserToken: string;
  playlistId: string;
  trackIds: string[];
}): Promise<void> {
  const { developerToken, musicUserToken, playlistId, trackIds } = params;

  const res = await fetch(`${APPLE_MUSIC_API}/${playlistId}/tracks`, {
    method: "POST",
    headers: authHeaders(developerToken, musicUserToken),
    body: JSON.stringify({ data: toTrackData(trackIds) }),
  });

  if (!res.ok) {
    const text = await res.text().catch(() => "");
    throw new Error(
      `Apple Music add tracks failed: ${res.status} ${res.statusText} — ${text}`
    );
  }
}

/**
 * High-level: create a playlist for a round and add all tracks.
 */
export async function generateAppleMusicPlaylist(params: {
  developerToken: string;
  musicUserToken: string;
  roundTheme: string;
  leagueName: string;
  trackIds: string[];
}): Promise<{ playlistId: string }> {
  const { developerToken, musicUserToken, roundTheme, leagueName, trackIds } =
    params;

  const name = `${roundTheme} — ${leagueName}`;
  const description = "Round playlist generated by Music League";

  return createAppleMusicPlaylist({
    developerToken,
    musicUserToken,
    name,
    description,
    trackIds,
  });
}
