const SPOTIFY_API_BASE = "https://api.spotify.com/v1";
const MAX_TRACKS_PER_REQUEST = 100;

export async function getSpotifyUserId(accessToken: string): Promise<string> {
  const res = await fetch(`${SPOTIFY_API_BASE}/me`, {
    headers: { Authorization: `Bearer ${accessToken}` },
  });

  if (!res.ok) {
    throw new Error(`Failed to get Spotify user ID: ${res.status} ${res.statusText}`);
  }

  const data = (await res.json()) as { id: string };
  return data.id;
}

export async function createSpotifyPlaylist(params: {
  accessToken: string;
  userId: string;
  name: string;
  description?: string;
  isPublic?: boolean;
}): Promise<{ playlistId: string; externalUrl: string }> {
  const res = await fetch(
    `${SPOTIFY_API_BASE}/users/${encodeURIComponent(params.userId)}/playlists`,
    {
      method: "POST",
      headers: {
        Authorization: `Bearer ${params.accessToken}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        name: params.name,
        description: params.description ?? "",
        public: params.isPublic ?? true,
      }),
    }
  );

  if (!res.ok) {
    throw new Error(`Failed to create Spotify playlist: ${res.status} ${res.statusText}`);
  }

  const data = (await res.json()) as {
    id: string;
    external_urls: { spotify: string };
  };

  return {
    playlistId: data.id,
    externalUrl: data.external_urls.spotify,
  };
}

export async function addTracksToSpotifyPlaylist(params: {
  accessToken: string;
  playlistId: string;
  trackUris: string[];
}): Promise<void> {
  // Batch in groups of 100 (Spotify API limit)
  for (let i = 0; i < params.trackUris.length; i += MAX_TRACKS_PER_REQUEST) {
    const batch = params.trackUris.slice(i, i + MAX_TRACKS_PER_REQUEST);

    const res = await fetch(
      `${SPOTIFY_API_BASE}/playlists/${encodeURIComponent(params.playlistId)}/tracks`,
      {
        method: "POST",
        headers: {
          Authorization: `Bearer ${params.accessToken}`,
          "Content-Type": "application/json",
        },
        body: JSON.stringify({ uris: batch }),
      }
    );

    if (!res.ok) {
      throw new Error(
        `Failed to add tracks to Spotify playlist (batch starting at ${i}): ${res.status} ${res.statusText}`
      );
    }
  }
}

export async function generateSpotifyPlaylist(params: {
  accessToken: string;
  roundTheme: string;
  leagueName: string;
  trackIds: string[];
}): Promise<{ playlistId: string; externalUrl: string }> {
  const userId = await getSpotifyUserId(params.accessToken);

  const { playlistId, externalUrl } = await createSpotifyPlaylist({
    accessToken: params.accessToken,
    userId,
    name: `${params.roundTheme} — ${params.leagueName}`,
    description: "Round playlist generated by Music League",
    isPublic: true,
  });

  if (params.trackIds.length > 0) {
    const trackUris = params.trackIds.map((id) => `spotify:track:${id}`);
    await addTracksToSpotifyPlaylist({
      accessToken: params.accessToken,
      playlistId,
      trackUris,
    });
  }

  return { playlistId, externalUrl };
}
